// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2024 Sedecal S.A.
// This file is part of OzonobaricD.
// See LICENSE file for details.

import QtQuick 2.12
import QtQuick.LocalStorage 2.0
import "Database.js" as DB
import AppConstants 1.0
import AppImages 1.0
import AppStyle 1.0

Item {
    readonly property string dbVersion: "V0.R0.P0"

/*
    dbVersion log:
    22/07/2022 - V0.R0.P0: Development purposes.
*/

    function createConfigDB(){
        console.log("Filling configuration data base...")
        //                                                                                   P                                          S     S    S      S     S    S      S      S    S                                                                                     U
        //                                                                                   a                                          l     l    l      l     l    l      l      l    l               M      M      M      M      M                   A      C              n                                               V                                             I
        //                                              P                                    r                                          i     i    i      i     i    i      i      i    i               e      e      e      e      e                   l      o              i                                               a                                             c
        //                                              r                                    a                                          d     d    d      d     d    d      d      d    d      D        m      m      m      m      m                   t      n              t                                               l                                             o
        //                                              o                                    m                                                                                                 e                                                               v                                                                                                            n
        //                                              t                                                                        O      M     M    S      M     M    S      M      M    S      f        V      V      V      V      V    U              U                     C                                               C
        //                                              o                                    N                                   r      a     i    t      a     i    t      a      i    t               a      a      a      a      a    n              n      F              o                                               o                                             P
        //                                              c                                    a                                   d      x     n    e      x     n    e      x      n    e      V        l      l      l      l      l    i              i      a              l                                               l                                             a
        //                                              o                                    m                                   e                 p                 p                  p      a                                         t              t      c              o                                               o                                             t
        //                                              l                                    e                                   r      0     0    0      1     1    1      2      2    2      l        0      1      2      3      4    s              s      t              r                                               r                                             h

//      console.log("Inserting: ", DB.dbConfig_Insert( "syringe_auto",                      "concentration",                     0,    80,    1,   1,     0,    0,   0,     0,     0,   0,    15, "    10,    20,    30,    40,    50", "\u03BCg/Nml", "---", 1.0,           "deepskyblue",                                  "lightskyblue",                                "Images/OZONO_02.png" ))
        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.syringe_auto,         Const.param.edition.concentration,   0,    80,    1,   1,     0,    0,   0,     0,     0,   0,    15, "    10,    20,    30,    40,    50", "\u03BCg/Nml", "---", 1.0,           Style.param.edition.unitsColor.concentration,   Style.param.edition.mainColor.concentration,   Img.param.edition.concentration ))

        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.manual_syringe,       Const.param.edition.concentration,   0,    80,    1,   1,     0,    0,   0,     0,     0,   0,    15, "    10,    20,    30,    40,    50", "\u03BCg/Nml", "---", 1.0,           Style.param.edition.unitsColor.concentration,   Style.param.edition.mainColor.concentration,   Img.param.edition.concentration ))
        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.manual_syringe,       Const.param.edition.flow,            1,    40,   10,   1,     0,    0,   0,     0,     0,   0,    30, "    10,    20,    25,    30,    40", "l/h",         "l/m", 0.016666667,   Style.param.edition.unitsColor.flow,            Style.param.edition.mainColor.flow,            Img.param.edition.flow ))

        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.continuous,           Const.param.edition.concentration,   0,    80,    1,   1,     0,    0,   0,     0,     0,   0,    15, "    20,    30,    40,    50,    60", "\u03BCg/Nml", "---", 1.0,           Style.param.edition.unitsColor.concentration,   Style.param.edition.mainColor.concentration,   Img.param.edition.concentration ))
        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.continuous,           Const.param.edition.flow,            1,    50,   10,   1,     0,    0,   0,     0,     0,   0,    30, "    10,    20,    30,    40,    50", "l/h",         "l/m", 0.016666667,   Style.param.edition.unitsColor.flow,            Style.param.edition.mainColor.flow,            Img.param.edition.flow ))
        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.continuous,           Const.param.edition.time,            2,    30,    1,   1,     0,    0,   0,     0,     0,   0,    15, "     5,    10,    20,    25,    30", "min",         "---", 1.2,           Style.param.edition.unitsColor.time,            Style.param.edition.mainColor.time,            Img.param.edition.time ))

        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.open_bag,             Const.param.edition.concentration,   0,    80,    1,   1,     0,    0,   0,     0,     0,   0,    40, "    40,    50,    60,    70,    80", "\u03BCg/Nml", "---", 1.0,           Style.param.edition.unitsColor.concentration,   Style.param.edition.mainColor.concentration,   Img.param.edition.concentration ))
        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.open_bag,             Const.param.edition.flow,            1,    50,   10,   1,     0,    0,   0,     0,     0,   0,    30, "    30,    35,    40,    45,    50", "l/h",         "l/m", 0.016666667,   Style.param.edition.unitsColor.flow,            Style.param.edition.mainColor.flow,            Img.param.edition.flow ))
        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.open_bag,             Const.param.edition.time,            2,    30,    1,   1,     0,    0,   0,     0,     0,   0,    15, "     5,    10,    15,    20,    25", "min",         "---", 1.2,           Style.param.edition.unitsColor.time,            Style.param.edition.mainColor.time,            Img.param.edition.time ))
        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.open_bag,             Const.param.edition.vacuum_time,     3,   300,   10,   1,     0,    0,   0,     0,     0,   0,    50, "    30,   100,   150,   200,   250", "sec",         "---", 1.3,           Style.param.edition.unitsColor.vacuum_time,     Style.param.edition.mainColor.vacuum_time,     Img.param.edition.vacuum_time ))

        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.closed_bag,           Const.param.edition.vacuum_time,     0,   180,   10,   1,     0,    0,   0,     0,     0,   0,    30, "    30,    60,    90,   120,   150", "sec",         "---", 1.3,           Style.param.edition.unitsColor.vacuum_time,     Style.param.edition.mainColor.vacuum_time,     Img.param.edition.vacuum_time ))
        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.closed_bag,           Const.param.edition.concentration,   1,    80,    1,   1,     0,    0,   0,     0,     0,   0,    40, "    40,    50,    60,    70,    80", "\u03BCg/Nml", "---", 1.0,           Style.param.edition.unitsColor.concentration,   Style.param.edition.mainColor.concentration,   Img.param.edition.concentration ))
        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.closed_bag,           Const.param.edition.c_bag_volume,    2,    30,    1,   1,     0,    0,   0,     0,     0,   0,     5, "     2,     4,     6,     8,    10", "l",           "---", 1.4,           Style.param.edition.unitsColor.c_bag_volume,    Style.param.edition.mainColor.c_bag_volume,    Img.param.edition.c_bag_volume ))
        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.closed_bag,           Const.param.edition.waiting_time,    3,    30,    5,   1,     0,    0,   0,     0,     0,   0,    20, "    10,    15,    20,    25,    30", "min",         "---", 1.2,           Style.param.edition.unitsColor.waiting_time,    Style.param.edition.mainColor.waiting_time,    Img.param.edition.waiting_time ))

        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.vaginal_insufflation, Const.param.edition.concentration,   0,    60,    1,   1,     0,    0,   0,     0,     0,   0,    30, "     5,    10,    15,    20,    30", "\u03BCg/Nml", "---", 1.0,           Style.param.edition.unitsColor.concentration,   Style.param.edition.mainColor.concentration,   Img.param.edition.concentration ))
        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.vaginal_insufflation, Const.param.edition.flow,            1,    30,   10,   1,     0,    0,   0,     0,     0,   0,    10, "    10,    15,    20,    25,    30", "l/h",         "l/m", 0.016666667,   Style.param.edition.unitsColor.flow,            Style.param.edition.mainColor.flow,            Img.param.edition.flow ))
        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.vaginal_insufflation, Const.param.edition.time,            2,    30,    1,   1,     0,    0,   0,     0,     0,   0,    10, "     5,    10,    15,    20,    25", "min",         "---", 1.2,           Style.param.edition.unitsColor.time,            Style.param.edition.mainColor.time,            Img.param.edition.time ))

        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.rectal_insufflation,  Const.param.edition.concentration,   0,    60,    1,   1,     0,    0,   0,     0,     0,   0,    20, "     5,    10,    15,    20,    30", "\u03BCg/Nml", "---", 1.0,           Style.param.edition.unitsColor.concentration,   Style.param.edition.mainColor.concentration,   Img.param.edition.concentration ))
        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.rectal_insufflation,  Const.param.edition.flow,            1,    30,   10,   1,     0,    0,   0,     0,     0,   0,    10, "    10,    15,    20,    25,    30", "l/h",         "l/m", 0.016666667,   Style.param.edition.unitsColor.flow,            Style.param.edition.mainColor.flow,            Img.param.edition.flow ))
        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.rectal_insufflation,  Const.param.edition.i_rectal_volume, 2,  1000,    1,   1,     0,    0,   0,     0,     0,   0,   200, "    20,   100,   200,   500,   800", "ml",          "---", 1.4,           Style.param.edition.unitsColor.i_rectal_volume, Style.param.edition.mainColor.i_rectal_volume, Img.param.edition.i_rectal_volume ))

        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.dose,                 Const.param.edition.concentration,   0,    80,    1,   1,     0,    0,   0,     0,     0,   0,    40, "    10,    20,    30,    40,    50", "\u03BCg/Nml", "---", 1.0,           Style.param.edition.unitsColor.concentration,   Style.param.edition.mainColor.concentration,   Img.param.edition.concentration ))
        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.dose,                 Const.param.edition.dose,            1,  5000,  500,  50, 20000, 5000, 100, 40000, 20000, 100, 10000, "  1000,  2000,  4000, 10000, 30000", "\u03BCg",     "---", 1.0,           Style.param.edition.unitsColor.dose,            Style.param.edition.mainColor.dose,            Img.param.edition.dose ))

        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.vacuum_time,          Const.param.edition.vacuum_time,     0,   600,    5,   1,     0,    0,   0,     0,     0,   0,   120, "    30,   120,   240,   360,   480", "sec",         "---", 1.3,           Style.param.edition.unitsColor.vacuum_time,     Style.param.edition.mainColor.vacuum_time,     Img.param.edition.vacuum_time ))
        console.log("Inserting: ", DB.dbConfig_Insert( Const.protocol.vacuum_pressure,      Const.param.edition.vacuum_press,    0,  -100, -800,   1,     0,    0,   0,     0,     0,   0,  -600, "  -150,  -300,  -450,  -600,  -750", "mbar",        "Psi", 0.0145038,     Style.param.edition.unitsColor.vacuum_press,    Style.param.edition.mainColor.vacuum_press,    Img.param.edition.vacuum_press ))

        console.log("End of configuration data base filling...")
    }

    function createStorageDB(){
        console.log("Filling storage data base...")       
//                                                               * use '_,_' as name & MAC separator
//      console.log("Inserting: ", DB.dbStorage_Insert(dbVersion, "RN4870-XXYY_,_??:??:??:??:??:??", "english", "international", "OzonobaricD", 0, 20, 30, 0, 120))
        console.log("Inserting: ", DB.dbStorage_Insert(dbVersion, "",                                "english", "international", "OzonobaricD", 0, 30, 30, 0, 120))

        console.log("End of configuration data base filling...")
    }

    function createLangDB(){
        console.log("Filling language data base...")
//                                                   language     press_temp                 dev_info                        sw_versions                        interface         control         database           gui     gen_time                 units_lang               bt_connection             load_param                   dev_name                   dev_parameters   startup_results               link_generator          reset_gen_time                        save_param                    generation_mode            pressure_cal                    flow_cal                   o3_cal               period_cal                   step_desc   press_cal_desc_1                                    press_cal_desc_2                           flow_cal_desc_1                    flow_cal_desc_2                  o3_cal_desc_1                  o3_cal_desc_2                  o3_cal_desc_3                  o3_cal_desc_4
        console.log("Inserting: ", DB.dbLang_Insert("english",   "Pressure & Temperature",  "Device information",           "SW versions",                     "Interface",      "Control",      "Data base",       "Gui",  "Generation time",       "Units & Language",      "Bluetooth connection",   "Load parameters",           "Device name",             "Parameters",    "Start up results",           "Link generator",       "Reset generation time",              "Save parameters",            "Generation mode",         "Pressure calibration",         "Flow calibration",        "O3 calibration",    "Period calibration",        "Step",     "Introduce current pressure value (mbar)",          "Increase pressure 500 mbar",              "Try to fix 30 l/h (0,5 l/min)",   "External measurement (l/min)",  "Preparing O3 sensor",         "Try to fix 60 \u03BCg/Nml",   "Try to fix 15 \u03BCg/Nml",   "Try to fix 1 \u03BCg/Nml") )
        console.log("Inserting: ", DB.dbLang_Insert("spanish",   "Presión y temperatura",   "Información del dispositivo",  "Versiones de SW",                 "Interface",      "Control",      "Base de datos",   "Gui",  "Tiempo de generación",  "Unidades e idioma",     "Conexión bluetooth",     "Carga de parámetros",       "Nombre del dispositivo",  "Parámetros",    "Resultado del arranque",     "Generador de enlace",  "Reiniciar tiempo de generación",     "Salvar parámetros",          "Modo de generación",      "Calibración de presión",       "Calibración de caudal",   "Calibración de O3", "Calibración de periodos",   "Paso",     "Introducir valor de presión actual (mbar)",        "Aumentar la presión 500 mbar",            "Ajustar 30 l/h (0,5 l/min)",      "Medida externa (l/min)",        "Preparando sensor de O3",     "Ajustar 60 \u03BCg/Nml",      "Ajustar 15 \u03BCg/Nml",      "Ajustar 1 \u03BCg/Nml") )
        console.log("Inserting: ", DB.dbLang_Insert("portugese", "Pressão e temperatura",   "Informação de dispositivo",    "Versões de SW",                   "Interface",      "Ao controle",  "Base de dados",   "Gui",  "Tempo de geração",      "Unidades e idioma",     "Conexão bluetooth",      "Carregamento de parâmetro", "Nome do dispositivo",     "Parâmetros",    "Resultado da inicialização", "Gerador de links",     "Redefinir o tempo de desova",        "salvar parâmetros",          "Modo de geração",         "Calibração de pressão",        "Calibração de fluxo",     "Calibração de O3",  "Calibração do período",     "Etapa",    "Insira o valor de pressão atual (mbar)",           "Aumentar a pressão em 500 mbar",          "Ajustar 30 l/h (0,5 l/min)",      "Medida externa (l/min)",        "Preparando o sensor de O3",   "Ajustar 60 \u03BCg/Nml",      "Ajustar 15 \u03BCg/Nml",      "Ajustar 1 \u03BCg/Nml") )
        console.log("Inserting: ", DB.dbLang_Insert("german",    "Druck und Temperatur",    "Geräteinformation",            "SW-Versionen",                    "Schnittstelle",  "Kontrolle",    "Datenbank",       "Gui",  "Generationszeit",       "Einheiten und Sprache", "Bluetooth-Verbindung",   "Laden von Parametern",      "Gerätename",              "Parameter",     "Boot-Ergebnis",              "Link-Generator",       "Spawnzeit zurücksetzen",             "Parameter speichern",        "Generatie modus",         "Druckkalibrierung",            "Durchflusskalibrierung",  "O3-Kalibrierung",   "Periodenkalibrierung",      "Bühne",    "Aktuellen Druckwert eingeben (mbar)",              "Druckerhöhung 500 mbar",                  "Anpassen 30 l/h (0,5 l/min)",     "Externe Maßnahme (l/min)",      "O3 Sensor vorbereiten",       "Anpassen 60 \u03BCg/Nml",     "Anpassen 15 \u03BCg/Nml",     "Anpassen 1 \u03BCg/Nml") )
        console.log("Inserting: ", DB.dbLang_Insert("french",    "Pression et température", "Informations sur l'appareil",  "Versions SW",                     "Interface",      "Contrôler",    "Base de données", "Gui",  "Temps de génération",   "Unités et langue",      "Connexion bluetooth",    "Chargement des paramètres", "Nom de l'appareil",       "Paramètres",    "Résultat de démarrage",      "Générateur de liens",  "Réinitialiser l'heure d'apparition", "Enregistrer les paramètres", "Mode de génération",      "Étalonnage de la pression",    "Étalonnage du débit",     "Étalonnage O3",     "Période d'étalonnage",      "Étape",    "Entrer la valeur de pression actuelle (mbar)",     "Augmenter la pression de 500 mbar",       "Régler 30 l/h (0,5 l/min)",       "Mesure externe (l/min)",        "Préparation du capteur O3",   "Régler 60 \u03BCg/Nml",       "Régler 15 \u03BCg/Nml",       "Régler 1 \u03BCg/Nml") )
        console.log("Inserting: ", DB.dbLang_Insert("italian",   "Pressione e temperatura", "Informazioni sul dispositivo", "Versioni SW",                     "Interfaccia",    "Controllo",    "Banca dati",      "Gui",  "Tempo di generazione",  "Unità e lingua",        "Connessione bluetooth",  "Caricamento dei parametri", "Nome del dispositivo",    "Parametri",     "Risultato di avvio",         "Generatore di link",   "Reimposta il tempo di spawn",        "Salvare i parametri",        "Modalità di generazione", "Calibrazione della pressione", "Calibrazione del flusso", "Calibrazione O3",   "Calibrazione del periodo",  "Fase",     "Immettere il valore di pressione attuale (mbar)",  "Aumentare la pressione di 500 mbar",      "Regolare 30 l/h (0,5 l/min)",     "Misura esterna (l/min)",        "Preparazione del sensore O3", "Regolare 60 \u03BCg/Nml",     "Regolare 15 \u03BCg/Nml",     "Regolare 1 \u03BCg/Nml") )
        console.log("Inserting: ", DB.dbLang_Insert("russian",   "давление и температура",  "Информация об устройстве",     "Версии программного обеспечения", "Интерфейс",      "Контроль",     "База данных",     "Gui",  "время генерации",       "Единицы и язык",        "Bluetooth-соединение",   "Загрузка параметров",       "Имя устройства",          "Параметры",     "Результат загрузки",         "генератор ссылок",     "Сбросить время появления",           "сохранить параметры",        "Режим генерации",         "калибровка давления",          "Калибровка расхода",      "Калибровка озона",  "Калибровка периода",        "сцена",    "Введите текущее значение давления (mbar)",         "Увеличить давление на 500 мбар",          "Регулировать 30 l/h (0,5 l/min)", "внешняя мера (l/min)",          "Подготовка датчика O3",       "Регулировать 60 \u03BCg/Nml", "Регулировать 15 \u03BCg/Nml", "Регулировать 1 \u03BCg/Nml") )
        console.log("Inserting: ", DB.dbLang_Insert("chinesse",  "压力和温度",                "设备信息",                      "软件版本",                         "界面",            "控制",          "数据库",           "Gui",  "世代时间",               "单位和语言",              "蓝牙连接",                "参数加载",                   "设备名称",                  "参数",          "启动结果",                     "链接生成器",            "重置生成时间",                         "保存参数",                    "生成方式",                  "压力校准 ",                      "流量校准",                 "臭氧校准",           "周期校准",                    "阶段",     "输入当前压力值 (mbar)",                              "增加壓力 500 mbar",                         "调整 30 l/h (0,5 l/min)",         "外部措施 (l/min)",                "准备 O3 传感器",               "外部措施 60 \u03BCg/Nml",       "外部措施 15 \u03BCg/Nml",      "外部措施 1 \u03BCg/Nml") )
//      console.log("Inserting: ", DB.dbLang_Insert("template",  "----",                    "----",                         "----",                            "----",           "----",         "----",            "----", "----",                  "----",                  "----",                   "----",                      "----",                    "----",          "----",                       "----",                 "----",                               "----",                       "----",                    "----",                         "----",                    "----",              "----",                      "----",     "----",                                             "----"                                     "----",                             "----",                          "----",                       "----",                         "----",                        "----") )

        console.log("End of language data base filling...")
    }

    //              Help view based on external apps
//    function createHelpDB(){
//        console.log("Filling help resources data base...")
////                                                   protocol                              namual                            tutorial video                        diagram                              protocol video
//        console.log("Inserting: ", DB.dbHelp_Insert(Const.protocol.syringe_auto,          "Syringe auto help.pdf",          "Syringe auto tutorial.mp4",          "Syringe auto diagram.png",          "Syringe auto protocol.mp4") )
//        console.log("Inserting: ", DB.dbHelp_Insert(Const.protocol.manual_syringe,        "Syringe manual help.pdf",        "Syringe manual tutorial.mp4",        "Syringe manual diagram.png",        "Syringe manual protocol.mp4") )
//        console.log("Inserting: ", DB.dbHelp_Insert(Const.protocol.continuous,            "O3 continuous help.pdf",         "O3 continuous tutorial.mp4",         "O3 continuous diagram.png",         "O3 continuous protocol.mp4") )
//        console.log("Inserting: ", DB.dbHelp_Insert(Const.protocol.open_bag,              "Open bag help.pdf",              "Open bag tutorial.mp4",              "Open bag diagram.png",              "Open bag protocol.mp4") )
//        console.log("Inserting: ", DB.dbHelp_Insert(Const.protocol.closed_bag,            "Closed bag help.pdf",            "Closed bag tutorial.mp4",            "Closed bag diagram.png",            "Closed bag protocol.mp4") )
//        console.log("Inserting: ", DB.dbHelp_Insert(Const.protocol.vaginal_insufflation,  "Vaginal insufflation help.pdf",  "Vaginal insufflation tutorial.mp4",  "Vaginal insufflation diagram.png",  "Vaginal insufflation protocol.mp4") )
//        console.log("Inserting: ", DB.dbHelp_Insert(Const.protocol.rectal_insufflation,   "Rectal insufflation help.pdf",   "Rectal insufflation tutorial.mp4",   "Rectal insufflation diagram.png",   "Rectal insufflation protocol.mp4") )
//        console.log("Inserting: ", DB.dbHelp_Insert(Const.protocol.dose,                  "Dose help.pdf",                  "Dose tutorial.mp4",                  "Dose diagram.png",                  "Dose protocol.mp4") )
//        console.log("Inserting: ", DB.dbHelp_Insert(Const.protocol.vacuum_time,           "Time vacuum help.pdf",           "Time vacuum tutorial.mp4",           "Time vacuum diagram.png",           "Time vacuum protocol.mp4") )
//        console.log("Inserting: ", DB.dbHelp_Insert(Const.protocol.vacuum_pressure,       "Pressure vacuum help.pdf",       "Pressure vacuum tutorial.mp4",       "Pressure vacuum diagram.png",       "Pressure vacuum protocol.mp4") )
//        console.log("Inserting: ", DB.dbHelp_Insert("protocolEditingParameter",           "",                               "Magnitude selector tutorial.mp4",    "",                                  "") )
//        console.log("Inserting: ", DB.dbHelp_Insert("gadgetEditing",                      "",                               "Pressure gadget tutorial.mp4",       "",                                  "") )

//        console.log("End of help resources data base filling...")
//    }

    function createHelpDB(){
        console.log("Filling help resources data base...")
//                                                   protocol                              namual                              tutorial video                          diagram                              protocol video
        console.log("Inserting: ", DB.dbHelp_Insert(Const.protocol.syringe_auto,          "Syringe auto help QR.png",          "Syringe auto tutorial QR.png",         "Syringe auto diagram.png",          "Syringe auto protocol QR.png") )
        console.log("Inserting: ", DB.dbHelp_Insert(Const.protocol.manual_syringe,        "Syringe manual help QR.png",        "Syringe manual tutorial QR.png",       "Syringe manual diagram.png",        "Syringe manual protocol QR.png") )
        console.log("Inserting: ", DB.dbHelp_Insert(Const.protocol.continuous,            "O3 continuous help QR.png",         "O3 continuous tutorial QR.png",        "O3 continuous diagram.png",         "O3 continuous protocol QR.png") )
        console.log("Inserting: ", DB.dbHelp_Insert(Const.protocol.open_bag,              "Open bag help QR.png",              "Open bag tutorial QR.png",             "Open bag diagram.png",              "Open bag protocol QR.png") )
        console.log("Inserting: ", DB.dbHelp_Insert(Const.protocol.closed_bag,            "Closed bag help QR.png",            "Closed bag tutorial QR.png",           "Closed bag diagram.png",            "Closed bag protocol QR.png") )
        console.log("Inserting: ", DB.dbHelp_Insert(Const.protocol.vaginal_insufflation,  "Vaginal insufflation help QR.png",  "Vaginal insufflation tutorial QR.png", "Vaginal insufflation diagram.png",  "Vaginal insufflation protocol QR.png") )
        console.log("Inserting: ", DB.dbHelp_Insert(Const.protocol.rectal_insufflation,   "Rectal insufflation help QR.png",   "Rectal insufflation tutorial QR.png",  "Rectal insufflation diagram.png",   "Rectal insufflation protocol QR.png") )
        console.log("Inserting: ", DB.dbHelp_Insert(Const.protocol.dose,                  "Dose help QR.png",                  "Dose tutorial QR.png",                 "Dose diagram.png",                  "Dose protocol QR.png") )
        console.log("Inserting: ", DB.dbHelp_Insert(Const.protocol.vacuum_time,           "Time vacuum help QR.png",           "Time vacuum tutorial QR.png",           "Time vacuum diagram.png",           "Time vacuum protocol QR.png") )
        console.log("Inserting: ", DB.dbHelp_Insert(Const.protocol.vacuum_pressure,       "Pressure vacuum help QR.png",       "Pressure vacuum tutorial QR.png",       "Pressure vacuum diagram.png",       "Pressure vacuum protocol QR.png") )
        console.log("Inserting: ", DB.dbHelp_Insert("protocolEditingParameter",           "",                                  "Magnitude selector tutorial QR.png",    "",                                  "") )
        console.log("Inserting: ", DB.dbHelp_Insert("gadgetEditing",                      "",                                  "Pressure gadget tutorial QR.png",       "",                                  "") )

        console.log("End of help resources data base filling...")
    }



}
